// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlOZQjk3TK38wKoVlNQQ3uIv3_Qq4woyo',
    appId: '1:158414928669:web:cec215ee8e77b3360abff4',
    messagingSenderId: '158414928669',
    projectId: 'raseed-app-2f1f7',
    authDomain: 'raseed-app-2f1f7.firebaseapp.com',
    storageBucket: 'raseed-app-2f1f7.firebasestorage.app',
    measurementId: 'G-6C50LMHVRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuKJQ4qwEfw9NsvYBgrNiZAWX0BK91WkU',
    appId: '1:158414928669:android:8a9253ac78a3457d0abff4',
    messagingSenderId: '158414928669',
    projectId: 'raseed-app-2f1f7',
    storageBucket: 'raseed-app-2f1f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1GeXI9iQKZa26Ls_hPOtmZI2BszVs1Ow',
    appId: '1:158414928669:ios:db74870a783be48b0abff4',
    messagingSenderId: '158414928669',
    projectId: 'raseed-app-2f1f7',
    storageBucket: 'raseed-app-2f1f7.firebasestorage.app',
    iosClientId: '158414928669-74im08mp1k8s75efvrbel81fhe6929kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.raseedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1GeXI9iQKZa26Ls_hPOtmZI2BszVs1Ow',
    appId: '1:158414928669:ios:db74870a783be48b0abff4',
    messagingSenderId: '158414928669',
    projectId: 'raseed-app-2f1f7',
    storageBucket: 'raseed-app-2f1f7.firebasestorage.app',
    iosClientId: '158414928669-74im08mp1k8s75efvrbel81fhe6929kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.raseedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlOZQjk3TK38wKoVlNQQ3uIv3_Qq4woyo',
    appId: '1:158414928669:web:a79fed358b9321f80abff4',
    messagingSenderId: '158414928669',
    projectId: 'raseed-app-2f1f7',
    authDomain: 'raseed-app-2f1f7.firebaseapp.com',
    storageBucket: 'raseed-app-2f1f7.firebasestorage.app',
    measurementId: 'G-FJ1M97F3JR',
  );
}
